OPTIONS (skip=1)
Load data
'look at next line'
'rush b!!!!!!!!!!!!!!! gogogogogogogogogoogogo'
Append into table T_GJHJ_ZDF
fields terminated by x'09'
TRAILING NULLCOLS
(ID,NATIONAL_POSTAGE_ID,MAIL_NO,ORG_ID,ORG_NAME,TRANSPORT_TYPE,ORIGINAL_SEND_ORG,RECEIVED_ORG,PACKAGE_BARCODE,PACKAGE_WEIGHT INTEGER EXTERNAL,FULL_ROUTER_CODE,START_PORT,END_PORT,PACKAGE_NUM INTEGER EXTERNAL,RECEIVE_TIME date 'yyyy-MM-dd HH24:mi:ss',RECEIVE_ORG_CODE,RECEIVE_ORG_NAME,RECEIVE_PROVINCE_CODE,RECEIVE_PROVINCE_NAME,RECEIVE_CITY_CODE,RECEIVE_CITY_NAME,RECEIVE_DISTRICT_CODE,RECEIVE_DISTRICT_NAME,MAIL_WEIGHT,BUSINESS_TYPE_CODE,BUSINESS_TYPE_NAME,RECEIVE_COUNTRY,CUSTOMER_CODE,STANDARD_FEE DECIMAL EXTERNAL,DISCOUNT_AMOUNT DECIMAL EXTERNAL,BUSINESS_CLASSIFY_CODE,BUSINESS_CLASSIFY_NAME,PIECE_FEE_PERCENT DECIMAL EXTERNAL,WEIGHT_FEE_PERCENT DECIMAL EXTERNAL,REGISTER_FEE_PERCENT DECIMAL EXTERNAL,TERMINAL_FEE_SDR DECIMAL EXTERNAL,SDR DECIMAL EXTERNAL,TERMINAL_FEE_RMB DECIMAL EXTERNAL,SETTLE_DATE,BUSINESS_DATE)

