OPTIONS (skip=1)
Load data
'no one can put out your tongue and deep breaths at the same time'
'@_@'
Append into table T_GJHJ_YF
fields terminated by x'09'
TRAILING NULLCOLS
(ID,SEND_ORG,RECEIVE_ORG,TRANSPORT_TYPE,PACKAGE_TYPE_CODE,PACKAGE_WEIGHT INTEGER EXTERNAL,PACKAGE_BARCODE,FIRST_FLIGHT,PACKAGE_NUM INTEGER EXTERNAL,BACK_FLAG,BACK_REASON,VOYOGE,PLAN_VOYOGE,FULL_ROUTER_CODE,MAIL_NO,RECEIVE_TIME  date 'yyyy-MM-dd HH24:mi:ss',RECEIVE_ORG_CODE,RECEIVE_ORG_NAME,RECEIVE_PROVINCE_CODE,RECEIVE_PROVINCE_NAME,RECEIVE_CITY_CODE,RECEIVE_CITY_NAME,RECEIVE_DISTRICT_CODE,RECEIVE_DISTRICT_NAME,MAIL_WEIGHT INTEGER EXTERNAL,BUSINESS_TYPE,BUSINESS_NAME,RECEIVE_COUNTRY,CUSTOMER_CODE,STANDARD_FEE DECIMAL EXTERNAL,DISCOUNT_AMOUNT DECIMAL EXTERNAL,BUSINESS_CLASSIFY_CODE,BUSINESS_CLASSIFY_NAME,POSTAGE_PERCENT DECIMAL EXTERNAL,POSTAGE_FEE DECIMAL EXTERNAL,SETTLE_DATE,BUSINESS_DATE)

